/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calcubuttons;

/**
 *
 * @author VILLACORTA_COMP111
 */
public class calcu extends javax.swing.JFrame {

    /**
     * Creates new form calcu
     */
    double num1;
    double num2;
    double Result;
    String op;

    public calcu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton19 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jresult = new javax.swing.JLabel();
        jBtn1 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtnADD = new javax.swing.JButton();
        jBtn4 = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtnSUB = new javax.swing.JButton();
        jBtn7 = new javax.swing.JButton();
        jBtn8 = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtnMUL = new javax.swing.JButton();
        jBtndot = new javax.swing.JButton();
        jbtpms = new javax.swing.JButton();
        jBtnDIV = new javax.swing.JButton();
        jBtn0 = new javax.swing.JButton();
        jBtnequ = new javax.swing.JButton();
        jBtnDEL = new javax.swing.JButton();
        jBtnCE = new javax.swing.JButton();
        jBtnC = new javax.swing.JButton();

        jButton19.setFont(new java.awt.Font("Arial Black", 1, 25)); // NOI18N
        jButton19.setText("CE");

        jButton21.setFont(new java.awt.Font("Arial Black", 1, 25)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jresult.setBackground(new java.awt.Color(51, 51, 51));
        jresult.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jresult.setForeground(new java.awt.Color(0, 0, 0));
        jresult.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 14, 350, 72));

        jBtn1.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jBtn1.setText("1");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 90, 80));

        jBtn2.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jBtn2.setText("2");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 90, 80));

        jBtn3.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jBtn3.setText("3");
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 90, 80));

        jBtnADD.setBackground(new java.awt.Color(204, 51, 0));
        jBtnADD.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jBtnADD.setForeground(new java.awt.Color(0, 0, 0));
        jBtnADD.setText("+");
        jBtnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnADDActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 90, 80));

        jBtn4.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jBtn4.setText("4");
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 90, 80));

        jBtn5.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jBtn5.setText("5");
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 90, 80));

        jBtn6.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jBtn6.setText("6");
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 90, 80));

        jBtnSUB.setBackground(new java.awt.Color(204, 51, 0));
        jBtnSUB.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jBtnSUB.setText("-");
        jBtnSUB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSUBActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSUB, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 90, 80));

        jBtn7.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jBtn7.setText("7");
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 90, 80));

        jBtn8.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jBtn8.setText("8");
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn8ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 90, 80));

        jBtn9.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jBtn9.setText("9");
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 90, 80));

        jBtnMUL.setBackground(new java.awt.Color(204, 51, 0));
        jBtnMUL.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jBtnMUL.setText("*");
        jBtnMUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMULActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnMUL, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 90, 80));

        jBtndot.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jBtndot.setText(".");
        jBtndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtndotActionPerformed(evt);
            }
        });
        getContentPane().add(jBtndot, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 90, 80));

        jbtpms.setBackground(new java.awt.Color(204, 51, 0));
        jbtpms.setFont(new java.awt.Font("Arial Black", 1, 25)); // NOI18N
        jbtpms.setText("±");
        jbtpms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtpmsActionPerformed(evt);
            }
        });
        getContentPane().add(jbtpms, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 90, 80));

        jBtnDIV.setBackground(new java.awt.Color(204, 51, 0));
        jBtnDIV.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jBtnDIV.setText("/");
        jBtnDIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDIVActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDIV, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 90, 80));

        jBtn0.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jBtn0.setText("0");
        jBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn0ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 90, 80));

        jBtnequ.setBackground(new java.awt.Color(204, 51, 0));
        jBtnequ.setFont(new java.awt.Font("Arial Black", 1, 25)); // NOI18N
        jBtnequ.setText("=");
        jBtnequ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnequActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnequ, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 90, 80));

        jBtnDEL.setBackground(new java.awt.Color(153, 153, 153));
        jBtnDEL.setFont(new java.awt.Font("Arial Black", 1, 25)); // NOI18N
        jBtnDEL.setText("DEL");
        jBtnDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDELActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 90, 80));

        jBtnCE.setBackground(new java.awt.Color(153, 153, 153));
        jBtnCE.setFont(new java.awt.Font("Arial Black", 1, 25)); // NOI18N
        jBtnCE.setText("CE");
        jBtnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCEActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 90, 80));

        jBtnC.setBackground(new java.awt.Color(153, 153, 153));
        jBtnC.setFont(new java.awt.Font("Arial Black", 1, 25)); // NOI18N
        jBtnC.setText("C");
        jBtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 90, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed
        Enternumber("1");
    }//GEN-LAST:event_jBtn1ActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
        Enternumber("2");
    }//GEN-LAST:event_jBtn2ActionPerformed

    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn3ActionPerformed
        Enternumber("3");
    }//GEN-LAST:event_jBtn3ActionPerformed

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn4ActionPerformed
        Enternumber("4");
    }//GEN-LAST:event_jBtn4ActionPerformed

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn5ActionPerformed
        Enternumber("5");
    }//GEN-LAST:event_jBtn5ActionPerformed

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed
        Enternumber("6");
    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed
        Enternumber("7");
    }//GEN-LAST:event_jBtn7ActionPerformed

    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn8ActionPerformed
        Enternumber("8");
    }//GEN-LAST:event_jBtn8ActionPerformed

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed
        Enternumber("9");
    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn0ActionPerformed
        Enternumber("0");
    }//GEN-LAST:event_jBtn0ActionPerformed

    private void jBtnDIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDIVActionPerformed
        num1 = Double.parseDouble(jresult.getText());
        jresult.setText("");
        op = "/";
    }//GEN-LAST:event_jBtnDIVActionPerformed

    private void jBtnMULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMULActionPerformed
        num1 = Double.parseDouble(jresult.getText());
        jresult.setText("");
        op = "*";
    }//GEN-LAST:event_jBtnMULActionPerformed

    private void jBtnSUBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSUBActionPerformed
        num1 = Double.parseDouble(jresult.getText());
        jresult.setText("");
        op = "-";
    }//GEN-LAST:event_jBtnSUBActionPerformed

    private void jBtnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnADDActionPerformed
        num1 = Double.parseDouble(jresult.getText());
        jresult.setText("");
        op = "+";
    }//GEN-LAST:event_jBtnADDActionPerformed

    private void jBtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCActionPerformed
        jresult.setText("");
    }//GEN-LAST:event_jBtnCActionPerformed

    private void jBtnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCEActionPerformed
        jresult.setText("");
        String Fn, Sn;
        Fn = String.valueOf(num1);
        Sn = String.valueOf(num2);
        Fn = "";
        Sn = "";
    }//GEN-LAST:event_jBtnCEActionPerformed

    private void jBtnDELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDELActionPerformed
        String bs = null;
        if (jresult.getText().length() > 0) {
            StringBuilder sb = new StringBuilder(jresult.getText());
            sb.deleteCharAt(jresult.getText().length() - 1);
            String backSp = sb.toString();
            jresult.setText(backSp);
        }
    }//GEN-LAST:event_jBtnDELActionPerformed

    private void jBtndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtndotActionPerformed
        if (!jresult.getText().contains("."));
        {
            jresult.setText(jresult.getText() + jBtndot.getText());
    }
    }//GEN-LAST:event_jBtndotActionPerformed

    private void jBtnequActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnequActionPerformed
       num2= Double.parseDouble(jresult.getText());
       if (op == "+"){
           Result = num1 + num2;
       jresult.setText(String.valueOf(Result));}
       else  if (op == "-"){
           Result = num1 - num2;
       jresult.setText(String.valueOf(Result));}
        else  if (op == "*"){
           Result = num1 * num2;
       jresult.setText(String.valueOf(Result));}
        else  if (op == "/"){
           Result = num1 / num2;
       jresult.setText(String.valueOf(Result));}
       else {
                    jresult.setText("invalid");}
                  
    }//GEN-LAST:event_jBtnequActionPerformed

    private void jbtpmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtpmsActionPerformed
       double nums = Double.parseDouble (String.valueOf(jresult.getText()));
       nums = nums * (-1);
       jresult.setText(String.valueOf(nums));
    }//GEN-LAST:event_jbtpmsActionPerformed

    /**
     * @param args the command line arguments
     */
    private void Enternumber(String q) {
        String Nums = jresult.getText() + q;
        jresult.setText(Nums);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calcu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn0;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jBtnADD;
    private javax.swing.JButton jBtnC;
    private javax.swing.JButton jBtnCE;
    private javax.swing.JButton jBtnDEL;
    private javax.swing.JButton jBtnDIV;
    private javax.swing.JButton jBtnMUL;
    private javax.swing.JButton jBtnSUB;
    private javax.swing.JButton jBtndot;
    private javax.swing.JButton jBtnequ;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jbtpms;
    private javax.swing.JLabel jresult;
    // End of variables declaration//GEN-END:variables
}
