/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ordersystem;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import pos.pro.JpanelLoader;

/**
 *
 * @author Jassen
 */
public class AdminDashboard extends javax.swing.JFrame {
 JpanelLoader panelLoader = new JpanelLoader();
  private final String LOG_FILE_PATH = "customer_log.txt"; // Log file for customer actions
    public AdminDashboard() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HOME = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        customer = new javax.swing.JToggleButton();
        suppier = new javax.swing.JToggleButton();
        employee = new javax.swing.JToggleButton();
        product = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        loadpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(49, 121, 84));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel1.setText("Dashboad");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 280, 50));

        HOME.add(customer);
        customer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customer.setText("CUSTOMER");
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });
        jPanel1.add(customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 130, 50));

        HOME.add(suppier);
        suppier.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        suppier.setText("SUPPLIER ");
        suppier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppierActionPerformed(evt);
            }
        });
        jPanel1.add(suppier, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 130, 40));

        HOME.add(employee);
        employee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        employee.setText("EMPLOYEE");
        employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeActionPerformed(evt);
            }
        });
        jPanel1.add(employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 130, 40));

        HOME.add(product);
        product.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        product.setText("PRODUCT");
        product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productActionPerformed(evt);
            }
        });
        jPanel1.add(product, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 130, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("LOG OUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 100, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 190, 800));

        loadpanel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout loadpanelLayout = new javax.swing.GroupLayout(loadpanel);
        loadpanel.setLayout(loadpanelLayout);
        loadpanelLayout.setHorizontalGroup(
            loadpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        loadpanelLayout.setVerticalGroup(
            loadpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );

        getContentPane().add(loadpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1010, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void writeLog(String message) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(LOG_FILE_PATH, true))) {
            writer.write(java.time.LocalDateTime.now() + " - " + message);
            writer.newLine();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error writing to log file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
    writeLog("Customer button clicked");
        customer customerPanel = new customer();
        panelLoader.jPanelLoader(loadpanel, customerPanel);
    }//GEN-LAST:event_customerActionPerformed

    private void suppierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppierActionPerformed
       supplier sup = new supplier();
        panelLoader.jPanelLoader(loadpanel, sup);
    }//GEN-LAST:event_suppierActionPerformed

    private void employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeActionPerformed
    employee emp = new employee();
        panelLoader.jPanelLoader(loadpanel, emp);
    }//GEN-LAST:event_employeeActionPerformed

    private void productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productActionPerformed
       product pro = new product();
        panelLoader.jPanelLoader(loadpanel, pro);
    }//GEN-LAST:event_productActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // Confirm before logging out
    int confirmation = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?", "Log Out", JOptionPane.YES_NO_OPTION);
    
    if (confirmation == JOptionPane.YES_OPTION) {
        // Create a new instance of the login window and make it visible
        login loginForm = new login();
        loginForm.setVisible(true);
        
        // Close the current window
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(null, "Log out canceled.");
    }
    System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup HOME;
    private javax.swing.JToggleButton customer;
    private javax.swing.JToggleButton employee;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel loadpanel;
    private javax.swing.JToggleButton product;
    private javax.swing.JToggleButton suppier;
    // End of variables declaration//GEN-END:variables

  
}
