package ordersystem;


import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Jassen
 */
public class mainfram extends javax.swing.JFrame {
   
    private double total = 0.0;
    int x = 0;
    private double tax = 0.0;

    public mainfram() {
        initComponents();
        settime();
    }

    public boolean qtyiszero(int qty) {
          if (qty == 0) {} else{
        JOptionPane.showMessageDialog(null, "IF YOU WANT TO ADD MORE CLIK THE SPINNER");
        return true;
    } 
 return false;
    }

    public void reset() {
        total = 0.0;
        x = 0;
        tax = 0.0;
        totalbtn.setEnabled(true);
        jSpinner1.setValue(0);
        jSpinner2.setValue(0);
        jSpinner3.setValue(0);
        jSpinner4.setValue(0);
        jSpinner5.setValue(0);
        jSpinner6.setValue(0);
        jSpinner7.setValue(0);
        jSpinner8.setValue(0);
        jSpinner9.setValue(0);
        jTextFieldtax.setText("0.0");
        jTextFieldSUB.setText("0.0");
        jTextFieldTOTAL.setText("0.0");
        jTextArea1.setText("");
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        jCheckBox6.setSelected(false);
        jCheckBox7.setSelected(false);
        jCheckBox8.setSelected(false);
        jCheckBox9.setSelected(false);
        jTextFieldtax.setText("0.0");
        jTextFieldSUB.setText("0.0");
        jTextFieldTOTAL.setText("0.0");
    }
 private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {                                             
        int confirmation = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?", "Log Out", JOptionPane.YES_NO_OPTION);
        
        if (confirmation == JOptionPane.YES_OPTION) {
            login loginForm = new login();
            loginForm.setVisible(true);
            this.dispose();
        }
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabeltime = new javax.swing.JLabel();
        jLabeldate = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        totalbtn = new javax.swing.JButton();
        jButtonreset = new javax.swing.JButton();
        receiptbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSpinner1 = new javax.swing.JSpinner();
        hot = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cold = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        pizza = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        donut = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        jLabel28 = new javax.swing.JLabel();
        burger = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jSpinner6 = new javax.swing.JSpinner();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        JUICE = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jSpinner7 = new javax.swing.JSpinner();
        jLabel40 = new javax.swing.JLabel();
        ICE = new javax.swing.JLabel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jSpinner8 = new javax.swing.JSpinner();
        jLabel46 = new javax.swing.JLabel();
        HALO = new javax.swing.JLabel();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jSpinner9 = new javax.swing.JSpinner();
        jLabel52 = new javax.swing.JLabel();
        MILK = new javax.swing.JLabel();
        jCheckBox9 = new javax.swing.JCheckBox();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jTextFieldTOTAL = new javax.swing.JTextField();
        jTextFieldtax = new javax.swing.JTextField();
        jTextFieldSUB = new javax.swing.JTextField();
        jTexttime = new javax.swing.JLabel();
        jTexttime1 = new javax.swing.JLabel();
        jTextdate = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(49, 121, 84));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel1.setText("Dashboad");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 280, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 110, 50));

        totalbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalbtn.setText("TOTAL");
        totalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalbtnActionPerformed(evt);
            }
        });
        jPanel1.add(totalbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 110, 60));

        jButtonreset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonreset.setText("RESET");
        jButtonreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonresetActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 110, 50));

        receiptbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        receiptbtn.setText("RECEIRPT");
        receiptbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptbtnActionPerformed(evt);
            }
        });
        jPanel1.add(receiptbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 110, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 190, 780));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setText("MENU ITEMS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        jPanel2.setBackground(new java.awt.Color(49, 121, 84));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("PURCHSE:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 70, 20));

        jLabel5.setText("PRICE:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 50, 20));

        jLabel6.setText("QUANTITY:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 70, 20));

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 20, -1));
        jPanel2.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 50, 20));

        hot.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hot.setText("HOT COFFEE");
        jPanel2.add(hot, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 80, -1));

        jLabel8.setText("2.0$");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 30, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\specialty-coffee-cappuccino-latte-hot-chocolate-mocha.jpg")); // NOI18N
        jLabel7.setText("jLabel3");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 130));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 180, 210));

        jPanel3.setBackground(new java.awt.Color(49, 121, 84));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cold.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cold.setText("COLD COFFEE");
        jPanel3.add(cold, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel12.setText("QUANTITY:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 70, 20));

        jLabel11.setText("PRICE:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 50, 20));

        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 20, -1));

        jLabel10.setText("PURCHSE:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 70, 20));

        jLabel14.setText("5.0$");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));
        jPanel3.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 50, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Perfect-Iced-CoffeeIMG_0074.jpg"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 220, 130));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 180, 210));

        jPanel4.setBackground(new java.awt.Color(49, 121, 84));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setText("8.0$");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));
        jPanel4.add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 50, 20));

        jLabel16.setText("QUANTITY:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 70, 20));

        pizza.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pizza.setText("PIZZA");
        jPanel4.add(pizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel19.setText("PURCHSE:");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 70, 20));

        jLabel17.setText("PRICE:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 50, 20));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dominos-MeatZZa-Pizza.jpg"))); // NOI18N
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 130));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 180, 210));

        jPanel11.setBackground(new java.awt.Color(49, 121, 84));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setText("4.0$");
        jPanel11.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));
        jPanel11.add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 50, 20));

        jLabel22.setText("QUANTITY:");
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 70, 20));

        donut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        donut.setText("DONUT");
        jPanel11.add(donut, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel11.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel24.setText("PURCHSE:");
        jPanel11.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 70, 20));

        jLabel25.setText("PRICE:");
        jPanel11.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 50, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stacked-chocolate-glazed-donuts-700x1050.jpg"))); // NOI18N
        jPanel11.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 130));

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 180, 210));

        jPanel12.setBackground(new java.awt.Color(49, 121, 84));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setText("10.0$");
        jPanel12.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 60, -1));
        jPanel12.add(jSpinner5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 50, 20));

        jLabel28.setText("QUANTITY:");
        jPanel12.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 70, 20));

        burger.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        burger.setText("BURGER");
        jPanel12.add(burger, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel12.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 20, -1));

        jLabel30.setText("PURCHSE:");
        jPanel12.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 70, 20));

        jLabel31.setText("PRICE:");
        jPanel12.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 50, 20));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/433534.jpg"))); // NOI18N
        jPanel12.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 130));

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 180, 210));

        jPanel13.setBackground(new java.awt.Color(49, 121, 84));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setText("3.0$");
        jPanel13.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));
        jPanel13.add(jSpinner6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 50, 20));

        jLabel34.setText("QUANTITY:");
        jPanel13.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 70, 20));
        jPanel13.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        jPanel13.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel36.setText("PURCHSE:");
        jPanel13.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 70, 20));

        jLabel37.setText("PRICE:");
        jPanel13.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 50, 20));

        JUICE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JUICE.setText("JUICE");
        jPanel13.add(JUICE, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 37, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\fresh-orange-juice-4.jpg")); // NOI18N
        jPanel13.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 130));

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 180, 210));

        jPanel14.setBackground(new java.awt.Color(49, 121, 84));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setText("9.0$");
        jPanel14.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));
        jPanel14.add(jSpinner7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 50, 20));

        jLabel40.setText("QUANTITY:");
        jPanel14.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 20));

        ICE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ICE.setText("ICE CREAM");
        jPanel14.add(ICE, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        jPanel14.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel42.setText("PURCHSE:");
        jPanel14.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 70, 20));

        jLabel43.setText("PRICE:");
        jPanel14.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 60, 20));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chocolate-Ice-Cream-in-a-Dish-Square.jpg"))); // NOI18N
        jLabel26.setText("jLabel3");
        jPanel14.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 130));

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 180, 220));

        jPanel15.setBackground(new java.awt.Color(49, 121, 84));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setText("15.0$");
        jPanel15.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, 20));
        jPanel15.add(jSpinner8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 50, 20));

        jLabel46.setText("QUANTITY:");
        jPanel15.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 70, 30));

        HALO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        HALO.setText("HALO-HALO");
        jPanel15.add(HALO, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        jPanel15.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, 30));

        jLabel48.setText("PURCHSE:");
        jPanel15.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 70, 30));

        jLabel49.setText("PRICE:");
        jPanel15.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 60, 30));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/halo.jpg"))); // NOI18N
        jLabel29.setText("jLabel3");
        jPanel15.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 130));

        getContentPane().add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 180, 220));

        jPanel16.setBackground(new java.awt.Color(49, 121, 84));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel51.setText("9.0$");
        jPanel16.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));
        jPanel16.add(jSpinner9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 50, 20));

        jLabel52.setText("QUANTITY:");
        jPanel16.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 20));

        MILK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MILK.setText("MILK TEA");
        jPanel16.add(MILK, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        jPanel16.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel54.setText("PURCHSE:");
        jPanel16.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 70, 20));

        jLabel55.setText("PRICE:");
        jPanel16.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 50, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\Bubble-Milk-Tea-square.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel16.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 130));

        getContentPane().add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, 180, 220));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel57.setText("TOTAL:");
        jPanel5.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, 60, -1));

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel58.setText("TAX:");
        jPanel5.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 60, 30));

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel59.setText("SUBTOTAL:");
        jPanel5.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 90, -1));
        jPanel5.add(jTextFieldTOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 690, 150, 30));
        jPanel5.add(jTextFieldtax, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, 150, 30));
        jPanel5.add(jTextFieldSUB, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 650, 150, 30));
        jPanel5.add(jTexttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 30));
        jPanel5.add(jTexttime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 20));
        jPanel5.add(jTextdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 130, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 330, 530));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 360, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Confirm before logging out
    int confirmation = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?", "Log Out", JOptionPane.YES_NO_OPTION);
    
    if (confirmation == JOptionPane.YES_OPTION) {
        // Create a new instance of the login window and make it visible
        login loginForm = new login();
        loginForm.setVisible(true);
        
        // Close the current window
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(null, "Log out canceled.");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void totalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalbtnActionPerformed
        if (total == 0.0) {
            JOptionPane.showMessageDialog(null, "YOU HAVEN'T SELECTED ANY ITEMS");
        } else {
            jTextArea1.setText(jTextArea1.getText()
                    + "\n***************************************************************\n"
                    + "Tax:\t\t" + tax + "\n"
                    + "Sub Total:\t\t" + total + "\n"
                    + "Total:\t\t" + (total+tax) + "\n\n"
            +"\n*************************Thank You**********************\n");
        
    }  
    }//GEN-LAST:event_totalbtnActionPerformed
     public void dudate(){
    jTextFieldtax.setText(String.valueOf(String.format("%.2f",tax)));
     jTextFieldSUB.setText(String.valueOf(String.format("%.2f",total)));
      jTextFieldTOTAL.setText(String.valueOf(String.format("%.2f",total+tax)));
     }
    
    public void getTax(int t) {
        if (t >= 10.0 && t <= 20.0) {
        tax = 0.5;
    } else if (t > 20.0 && t <= 30.0) {
        tax = 1.0;
    } else if (t > 30.0 && t <= 40.0) {
        tax = 1.5;
    } else if (t > 40.0 && t <= 50.0) {
        tax = 2.0;
    } else if (t > 50.0 && t <= 60.0) {
        tax = 2.5;
    } else if (t > 60.0 && t <= 100.0) {
        tax = 3.0;
    } else if (t > 100.0 && t <= 500.0) {
        tax = 4.0;
    } else if (t > 500.0 && t <= 1000.0) {
        tax = 5.0;
    }
    }

    private void jButtonresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonresetActionPerformed
        reset();
    }//GEN-LAST:event_jButtonresetActionPerformed

    private void receiptbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptbtnActionPerformed
    try {
        // Show the content of the receipt (text area) in a dialog for confirmation
        String receiptText = jTextArea1.getText();  // Get the current text in jTextArea1
        JOptionPane.showMessageDialog(null, receiptText, "Receipt", JOptionPane.INFORMATION_MESSAGE);
        
        // Ask for confirmation before printing
        int confirmation = JOptionPane.showConfirmDialog(null, "Do you want to print this receipt?", "Confirm Print", JOptionPane.YES_NO_OPTION);
        if (confirmation == JOptionPane.YES_OPTION) {
            // If user confirms, attempt to print
            boolean printed = jTextArea1.print();
            
            // Provide feedback on whether printing was successful
            if (printed) {
                JOptionPane.showMessageDialog(null, "Receipt Printed Successfully.");
            } else {
                JOptionPane.showMessageDialog(null, "Printing failed or was canceled.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Receipt printing canceled.");
        }
    } catch (PrinterException ex) {
        // Handle PrinterException if printing fails
        JOptionPane.showMessageDialog(null, "Error printing receipt: " + ex.getMessage());
        ex.printStackTrace();
    }
    }//GEN-LAST:event_receiptbtnActionPerformed
    public void order() {
        jTextArea1.setText("*******************************ORDER**********************\n"
                + "Time: " + jTexttime.getText() + "  Date: " + jTextdate.getText() + "\n"
                + "***************************************************************\n"
                + "Item:\t\tPrice($)\n");

    }


    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        int qty = Integer.parseInt(jSpinner1.getValue().toString());
        if (qtyiszero(qty) && jCheckBox1.isSelected()) {
            x++;
            if (x == 1) {
                order();
            }
            double price = qty * 2.0;
            total += price;
            getTax((int) total);
            jTextArea1.setText(jTextArea1.getText() + x + "." + hot.getText() + "\t" + price + "\n");
            dudate();
        } else {
            jCheckBox1.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        int qty = Integer.parseInt(jSpinner2.getValue().toString());
        if (qtyiszero(qty) && jCheckBox2.isSelected()) {
            x++;
            if (x == 1) {
                order();
            }
            double price = qty * 5.0;
            total += price;
            getTax((int) total);
            jTextArea1.setText(jTextArea1.getText() + x + "." + cold.getText() + "\t" + price + "\n");
           dudate();
        } else {
            jCheckBox2.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        int qty = Integer.parseInt(jSpinner3.getValue().toString());
        if (qtyiszero(qty) && jCheckBox3.isSelected()) {
            x++;
            if (x == 1) {
                order();
            }
            double price = qty * 8.0;
            total += price;
            getTax((int) total);
             jTextArea1.setText(jTextArea1.getText() + x + "." + pizza.getText() + "\t\t" + price + "\n");
        dudate();
        } else {
            jCheckBox3.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        int qty = Integer.parseInt(jSpinner4.getValue().toString());
        if (qtyiszero(qty) && jCheckBox4.isSelected()) {
            x++;
            if (x == 1) {
                order();
            }
            double price = qty * 4.0;
            total += price;
            getTax((int) total);
            jTextArea1.setText(jTextArea1.getText() + x + "." + donut.getText() + "\t\t" + price + "\n");
        dudate();
        } else {
            jCheckBox4.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        int qty = Integer.parseInt(jSpinner5.getValue().toString());
        if (qtyiszero(qty) && jCheckBox5.isSelected()) {
            x++;
            if (x == 1) {
                order();
            }
            double price = qty * 10.0;
            total += price;
            getTax((int) total);
            jTextArea1.setText(jTextArea1.getText() + x + "." + burger.getText() + "\t\t" + price + "\n");
       dudate();
        } else {
            jCheckBox5.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        int qty = Integer.parseInt(jSpinner6.getValue().toString());
        if (qtyiszero(qty) && jCheckBox6.isSelected()) {
            x++;
            if (x == 1) {
                order();
            }
            double price = qty * 3.0;
            total += price;
            getTax((int) total);
            jTextArea1.setText(jTextArea1.getText() + x + "." + JUICE.getText() + "\t\t" + price + "\n");
       dudate();
        } else {
            jCheckBox6.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        int qty = Integer.parseInt(jSpinner7.getValue().toString());
        if (qtyiszero(qty) && jCheckBox7.isSelected()) {
            x++;
            if (x == 1) {
                order();
            }
            double price = qty * 9.0;
            total += price;
            getTax((int) total);
            jTextArea1.setText(jTextArea1.getText() + x + "." + ICE.getText() + "\t\t" + price + "\n");
       dudate();
        } else {
            jCheckBox7.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        int qty = Integer.parseInt(jSpinner8.getValue().toString());
        if (qtyiszero(qty) && jCheckBox8.isSelected()) {
            x++;
            if (x == 1) {
                order();
            }
            double price = qty * 15.0;
            total += price;
            getTax((int) total);
            jTextArea1.setText(jTextArea1.getText() + x + "." + HALO.getText() + "\t\t" + price + "\n");
       dudate();
        } else {
            jCheckBox8.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        int qty = Integer.parseInt(jSpinner9.getValue().toString());
        if (qtyiszero(qty) && jCheckBox9.isSelected()) {
            x++;
            if (x == 1) {
                order();
            }
            double price = qty * 9.0;
            total += price;
            getTax((int) total);
            jTextArea1.setText(jTextArea1.getText() + x + "." + MILK.getText() + "\t\t" + price + "\n");
      dudate();
        } else {
            jCheckBox9.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    public void settime() {
        new Thread(() -> {
            while (true) {
                try {
                    // Get the current date and time
                    Date now = new Date();

                    // Define the date and time formats
                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                    SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");

                    // Format the current date and time
                    String formattedDate = dateFormat.format(now);
                    String formattedTime = timeFormat.format(now);

                    // Update the labels with the current date and time (use invokeLater)
                    SwingUtilities.invokeLater(() -> {
                        jTextdate.setText("Date: " + formattedDate);
                        jTexttime.setText("Time: " + formattedTime);
                    });

                    // Wait for 1 second before updating again
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                    break; // Exit the loop if the thread is interrupted
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }).start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>      
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new mainfram().setVisible(true));
    }

    // Assuming the following methods exist, otherwise, define them properly

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HALO;
    private javax.swing.JLabel ICE;
    private javax.swing.JLabel JUICE;
    private javax.swing.JLabel MILK;
    private javax.swing.JLabel burger;
    private javax.swing.JLabel cold;
    private javax.swing.JLabel donut;
    private javax.swing.JLabel hot;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonreset;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabeldate;
    private javax.swing.JLabel jLabeltime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JSpinner jSpinner9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldSUB;
    private javax.swing.JTextField jTextFieldTOTAL;
    private javax.swing.JTextField jTextFieldtax;
    private javax.swing.JLabel jTextdate;
    private javax.swing.JLabel jTexttime;
    private javax.swing.JLabel jTexttime1;
    private javax.swing.JLabel pizza;
    private javax.swing.JButton receiptbtn;
    private javax.swing.JButton totalbtn;
    // End of variables declaration//GEN-END:variables
}
